### ISSUE TITLE
Running into issues on production deployment (heroku)

### ISSUE THREAD

**Issue by fyllepo** [Nix-wie-weg/ga_events#18]
It works completely fine in development, however on our live application there is no HTML injection at the bottom of the page. I'm tracking from the controller.

The JS is loading in fine, and I'm able to use GaEvents via the console. 

Using ruby 2.1.2, rails 4.1.5 on both dev/prod servers.

Any ideas?

**Comment by fyllepo** [comment]
After comparing the response, I get something odd.

Dev (just before ending </body>):
```<div data-ga-events='Form: Event - Polarised local parallelism|Submission|Fail|'></div>```

Production (cuts off everything after data-ga-events):
```<div data-ga-events```
Tracking from controller with:
```GaEvents::Event.new('Form: Event - ' + @event.name, 'Submission', 'Fail')```

**Comment by der-flo** [comment]
Can you provide a simple demo app showing the problem?

**Comment by sophiedeziel** [comment]
I have the same issue, but on my dev environment. 
It is actually worse than @fyllepo because it is stripped after `<div data-ga-e`. The tag not even complete...

My first guess would be it has something to do with the content-length in the response header...

**Comment by der-flo** [comment]
I just created a simple demo app with Rails 4.2.5 which doesn't show this problem.

@sophiedeziel: Which app server are you using? Can you provide a simple demo app showing the problem?

**Comment by sophiedeziel** [comment]
I can't give you a demo because it's a closed source app. I decided to implement my own solution using a `flash` to pass the event to the view and then fetching it with my own javascript. 

We are using Puma

**Comment by der-flo** [comment]
I did a quick check with Puma, my test app doesn't produce this error.

It's quite difficult for us to spot this bug without a failing test app.

**Comment by sophiedeziel** [comment]
I'll try to reproduce in a demo app if I have some time this week. I hope I can help soon.

**Comment by der-flo** [comment]
That would be awesome.
