### ISSUE TITLE
Events fire off twice on page refresh

### ISSUE THREAD

**Issue by dbrink79** [Nix-wie-weg/ga_events#19]
My app is calling the Server side call in a model.  Upon item creation in the model we fire the after_created callback to kick off the GA call.  Once the item is created in the model we redirect the user to the same page but with a reference to the comment/reply they just left.  

On page load the event fires off to GAU just fine.  However if you refresh the page or click on a link to leave the page and go else where on the site the event that was just submitted is resubmitted to GAU.  

Any suggestion how to get around this?  In debugging the middleware.rb file on refresh the call `if GaEvents::List.present? ` seems to fail so I'm not sure how its inserting the div again.

**Comment by dbrink79** [comment]
I ended up fixing the issue by overriding the middleware.rb file and before the inject_div method is called resetting the flash message for ga_events and resetting the list object back to nil.  This seems to do what I need it to.

**Comment by svenwin** [comment]
What Rails/Ruby version are you using? Could you please provide a simple rails demo app showing the problem? I cannot reproduce the error without further information.
